package cz.epokladny;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class bugreport implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.String description;
   private java.lang.String severity;
   private java.lang.String product;

   public bugreport()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public java.lang.String getSeverity()
   {
      return this.severity;
   }

   public void setSeverity(java.lang.String severity)
   {
      this.severity = severity;
   }

   public java.lang.String getProduct()
   {
      return this.product;
   }

   public void setProduct(java.lang.String product)
   {
      this.product = product;
   }

   public bugreport(java.lang.String name, java.lang.String description,
         java.lang.String severity, java.lang.String product)
   {
      this.name = name;
      this.description = description;
      this.severity = severity;
      this.product = product;
   }

}