package cz.epokladny;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String firstName;
   private java.lang.String lastName;
   private java.lang.String email;

   private java.util.List<java.lang.String> _links;

   public customer()
   {
   }

   public java.lang.String getFirstName()
   {
      return this.firstName;
   }

   public void setFirstName(java.lang.String firstName)
   {
      this.firstName = firstName;
   }

   public java.lang.String getLastName()
   {
      return this.lastName;
   }

   public void setLastName(java.lang.String lastName)
   {
      this.lastName = lastName;
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public java.util.List<java.lang.String> get_links()
   {
      return this._links;
   }

   public void set_links(java.util.List<java.lang.String> _links)
   {
      this._links = _links;
   }

   public customer(java.lang.String firstName, java.lang.String lastName,
         java.lang.String email, java.util.List<java.lang.String> _links)
   {
      this.firstName = firstName;
      this.lastName = lastName;
      this.email = email;
      this._links = _links;
   }

}