package cz.epokladny;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class newfeature implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String description;
   private java.lang.String acceptancecriteria;
   private java.util.Date targetfix;
   private java.lang.Boolean requiresdesign;
   private java.lang.Boolean requiresarchitecture;
   private java.lang.String project;

   public newfeature()
   {
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public java.lang.String getAcceptancecriteria()
   {
      return this.acceptancecriteria;
   }

   public void setAcceptancecriteria(java.lang.String acceptancecriteria)
   {
      this.acceptancecriteria = acceptancecriteria;
   }

   public java.util.Date getTargetfix()
   {
      return this.targetfix;
   }

   public void setTargetfix(java.util.Date targetfix)
   {
      this.targetfix = targetfix;
   }

   public java.lang.Boolean getRequiresdesign()
   {
      return this.requiresdesign;
   }

   public void setRequiresdesign(java.lang.Boolean requiresdesign)
   {
      this.requiresdesign = requiresdesign;
   }

   public java.lang.Boolean getRequiresarchitecture()
   {
      return this.requiresarchitecture;
   }

   public void setRequiresarchitecture(java.lang.Boolean requiresarchitecture)
   {
      this.requiresarchitecture = requiresarchitecture;
   }

   public java.lang.String getProject()
   {
      return this.project;
   }

   public void setProject(java.lang.String project)
   {
      this.project = project;
   }

   public newfeature(java.lang.String description,
         java.lang.String acceptancecriteria, java.util.Date targetfix,
         java.lang.Boolean requiresdesign,
         java.lang.Boolean requiresarchitecture, java.lang.String project)
   {
      this.description = description;
      this.acceptancecriteria = acceptancecriteria;
      this.targetfix = targetfix;
      this.requiresdesign = requiresdesign;
      this.requiresarchitecture = requiresarchitecture;
      this.project = project;
   }

}