package cz.epokladny;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class reclamationreport implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer timespent;
   private java.lang.String conclusion;
   private java.lang.Boolean fixed;
   private java.lang.String steps;

   public reclamationreport()
   {
   }

   public java.lang.Integer getTimespent()
   {
      return this.timespent;
   }

   public void setTimespent(java.lang.Integer timespent)
   {
      this.timespent = timespent;
   }

   public java.lang.String getConclusion()
   {
      return this.conclusion;
   }

   public void setConclusion(java.lang.String conclusion)
   {
      this.conclusion = conclusion;
   }

   public java.lang.Boolean getFixed()
   {
      return this.fixed;
   }

   public void setFixed(java.lang.Boolean fixed)
   {
      this.fixed = fixed;
   }

   public java.lang.String getSteps()
   {
      return this.steps;
   }

   public void setSteps(java.lang.String steps)
   {
      this.steps = steps;
   }

   public reclamationreport(java.lang.Integer timespent,
         java.lang.String conclusion, java.lang.Boolean fixed,
         java.lang.String steps)
   {
      this.timespent = timespent;
      this.conclusion = conclusion;
      this.fixed = fixed;
      this.steps = steps;
   }

}