package cz.epokladny;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class reclamationassesment implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Malfunction replicated")
   private java.lang.Boolean replicated;
   @org.kie.api.definition.type.Label("Frequency of malfunction")
   @org.kie.api.definition.type.Description("How many times does the malfunction occur?")
   private java.lang.String occurence;
   @org.kie.api.definition.type.Label("Estimated time to fix")
   @org.kie.api.definition.type.Description("Number of hours to fix the malfunction")
   private Integer estimation;

   public reclamationassesment()
   {
   }

   public java.lang.Boolean getReplicated()
   {
      return this.replicated;
   }

   public void setReplicated(java.lang.Boolean replicated)
   {
      this.replicated = replicated;
   }

   public java.lang.String getOccurence()
   {
      return this.occurence;
   }

   public void setOccurence(java.lang.String occurence)
   {
      this.occurence = occurence;
   }

   public java.lang.Integer getEstimation()
   {
      return this.estimation;
   }

   public void setEstimation(java.lang.Integer estimation)
   {
      this.estimation = estimation;
   }

   public reclamationassesment(java.lang.Boolean replicated,
         java.lang.String occurence, java.lang.Integer estimation)
   {
      this.replicated = replicated;
      this.occurence = occurence;
      this.estimation = estimation;
   }

}