package cz.epokladny;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class swissuereport implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.String stepstoreproduce;
   private java.lang.String environment;

   public swissuereport()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getStepstoreproduce()
   {
      return this.stepstoreproduce;
   }

   public void setStepstoreproduce(java.lang.String stepstoreproduce)
   {
      this.stepstoreproduce = stepstoreproduce;
   }

   public java.lang.String getEnvironment()
   {
      return this.environment;
   }

   public void setEnvironment(java.lang.String environment)
   {
      this.environment = environment;
   }

   public swissuereport(java.lang.String name,
         java.lang.String stepstoreproduce, java.lang.String environment)
   {
      this.name = name;
      this.stepstoreproduce = stepstoreproduce;
      this.environment = environment;
   }

}